export const actionTypes = {
  SET_THEME: "SET_THEME",
  SET_CURRENCIES: "SET_CURRENCIES",
  SET_TRUE_SOURCE_CURRENCIES: "SET_TRUE_SOURCE_CURRENCIES",
  SET_SELECTED_CURRENCY: "SET_SELECTED_CURRENCY",
  SET_CURRENCY_LIST_LOADING: "SET_CURRENCY_LIST_LOADING",
  SET_CURRENCY_LIST_ERROR: "SET_CURRENCY_LIST_ERROR",
};
